routes/web.php
<?php


Route::get('/', function () {
    return view('welcome');
});

//Auth::routes();

// Authentication Routes...



Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// switched off Registration Routes...
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');


Route::middleware(['auth'])->group(function () {

    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/home', 'DashboardController@index')->name('dashboard');

    Route::get('/bookings', 'BookingController@index')->name('all.bookings');
    Route::get('/bookings-json', 'BookingController@allBookingsJson')->name('all.bookings.json');

    Route::get('/bookings/{parameter}', 'BookingController@showSplitBooking')->name('split.bookings');
    Route::get('/bookings-json/{parameter}', 'BookingController@returnSplitBookingJson')->name('split.bookings.json');
    /*
     * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
     */
    Route::get('/customers', 'CustomerController@index')->name('all.customers');
    Route::get('/customers-json', 'CustomerController@allCustomersJson')->name('all.customers.json');
    Route::get('/customers-json/{id}', 'CustomerController@singleCustomersJson');
    Route::get('/customers/{customer}/edit', 'CustomerController@edit');
    Route::put('/customers/{customer}', 'CustomerController@update')->name('customers.update');;
    Route::delete('/customers/{customer}', 'CustomerController@delete');

    /*
     * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
     */
    Route::get('/drivers', 'DriverController@index')->name('all.drivers');
    Route::get('/drivers-json', 'DriverController@allDriverJson')->name('all.drivers.json');
    Route::get('/drivers-json/{driver}', 'DriverController@singleDriverJson');
    Route::get('/drivers/{driver}/edit', 'DriverController@edit');
    Route::get('/drivers/create', 'DriverController@create')->name('drivers.create');
    Route::post('/drivers', 'DriverController@store')->name('drivers.store');
    Route::put('/drivers/{driver}', 'DriverController@update')->name('all.driver.update');;
    Route::delete('/drivers/{driver}', 'DriverController@delete');
    /*
     * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
     */
    Route::get('/drivers/{driver}/payment', 'TransactionController@showPaymentPage')->name('driver.payment.create');
    Route::post('/drivers/{driver}/payment', 'TransactionController@paymentCalculate')->name('driver.payment.store');
    Route::get('/transaction', 'TransactionController@index')->name('all.transaction');
    Route::get('/transaction-json', 'TransactionController@allTransactionJson')->name('all.transaction.json');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::resource('rides', 'RideTypesController');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('currency-by-country/{countryName}', 'PatternController@getCurrencyByCountryName');
    Route::resource('patterns', 'PatternController')->except(['show']);
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::resource('helps', 'HelpTableController');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::resource('promocodes', 'PromocodeController')->except(['show', 'destroy']);
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('documents-json', 'DriverDocumentController@getDocumentJson')->name('driver-documents.json');
    Route::get('driver-documents/{driver}', 'DriverDocumentController@getAllDocumentsOfDriver');
    Route::resource('documents', 'DriverDocumentController')->except(['edit']);
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('feedbacks', 'FeedbackController@index')->name('feedbacks.index');
    Route::get('feedbacks-json', 'FeedbackController@getFeedbackJson')->name('feedbacks.json');
    Route::get('feedbacks/{feedback}', 'FeedbackController@show');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('requests', 'RequestController@index')->name('requests.index');
    Route::get('requests/{request}', 'RequestController@show');
    Route::get('requests-json', 'RequestController@getRequestsJson')->name('requests.json');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('fcms', 'NotificationController@viewFcmPage')->name('notifications.fcm');
    Route::put('fcms/{fcm}/edit', 'NotificationController@editFcm')->name('notification.fcm.update');

    Route::get('notifications-json', 'NotificationController@getNotificationJson')->name('notifications.json');

    Route::get('notifications', 'NotificationController@index')->name('notifications.index');
    Route::get('notifications/create', 'NotificationController@create')->name('notifications.create');
    Route::post('notifications', 'NotificationController@store')->name('notifications.store');
    /*
     * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
     */
    Route::get('settings', 'SettingController@edit')->name('settings.edit');
    Route::put('settings/{setting}/edit', 'SettingController@update')->name('settings.update');

});

Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');

app/Notification.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Notification extends Eloquent
{
    //
}

app/Http/Controllers/NotificationController.php
<?php

namespace App\Http\Controllers;

use App\FcmKey;
use App\Notification;
use Illuminate\Http\Request;

class NotificationController extends Controller
{

    /**
     * Show all FCM from fcmkey database.
     *
     */
    public function viewFcmPage(){

        $fcmKey = FcmKey::first();

        return view('admin.notifications.fcm_edit')->with('fcmKey', $fcmKey);
    }

    /**
     * edit single fcm
     *
     */
    public function editFcm(Request $request, FcmKey $fcm){

        $fcm->fcm_url = $request->fcm_url ;
        $fcm->fcm_key_id = $request->fcm_key_id ;
        $fcm->save();

        return redirect()->route('notification.fcm')->with('success', 'FCM Info Successfully Deleted');

    }

    /**
     * Display a listing of this Notifications.
     *
     */
    public function index()
    {
        return view('admin.notifications.index');
    }

    /**
     * Display a listing of this Notifications.
     *
     */
    public function getNotificationJson()
    {

        return response()->json([
            'aaData' => Notification::all()
        ]);
    }

    /**
     * Show the form for creating a new Notifications.
     *
     */
    public function create()
    {
        return view('admin.notifications.create');
    }

    /**
     * Store a newly created Notifications in storage.
     *
     */
    public function store(Request $request)
    {
        //
    }


}

resources/views/admin/notifications/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="bg-light lter b-b wrapper-md">
        <h1 class="m-n font-thin h3">Dashboard / Create Notifications</h1>
    </div>
    @include('admin.show_error_message')
    <div class="wrapper-md">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading font-bold">
                    <h4>Create A New Notifications </h4>
                </div>
                <div class="panel-body">
                    <form class="bs-example form-horizontal" action="{{route('notifications.store')}}" method="post"
                          enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="col-md-10 col-md-offset-1">
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Title</label>
                                <div class="col-lg-8">
                                    <input name="title" value="{{ old('title') }}" required type="text"
                                           class="form-control" placeholder="Please Enter Notifications Name">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Message</label>
                                <div class="col-lg-8">
                                    <textarea name="description"  placeholder="Please Enter Notification"  value="{{ old('description') }}"  type="number"
                                              class="form-control" ></textarea>
                                </div>
                            </div>



                            <div class="form-group">
                                <label class="col-lg-4 control-label">Base Price</label>
                                <div class="col-lg-8">
                                    <input name="base_price" value="{{ old('base_price') }}" required type="number"
                                           step="0.01" class="form-control" placeholder="Please Enter Base Price">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Minimum Notifications Fare</label>
                                <div class="col-lg-8">
                                    <input name="min_ride_fare" value="{{ old('min_ride_fare') }}" required
                                           type="number" step="0.01" class="form-control"
                                           placeholder="Please Enter Minimum Notifications Fare">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Kilometer Rate</label>
                                <div class="col-lg-8">
                                    <input name="km_rate" value="{{ old('km_rate') }}" required type="number"
                                           step="0.01" class="form-control" placeholder="Please Enter Kilometer Rate">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Minimum Rate</label>
                                <div class="col-lg-8">
                                    <input name="min_rate" value="{{ old('min_rate') }}" required type="number"
                                           step="0.01" class="form-control" placeholder="Please Enter Minimum Rate">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Location</label>
                                <div class="col-lg-8">
                                    <input name="location" id="location" required type="text"
                                           class="form-control" placeholder="Please Enter Location">
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="col-lg-4 col-md-offset-4">
                                            <input name="latitude" readonly required type="text"
                                                   class="form-control" placeholder="Latitude">
                                        </div>
                                        <div class="col-lg-4">
                                            <input name="longitude" readonly required type="text"
                                                   class="form-control" placeholder="Longitude">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Currency <small class="text-danger">*auto added</small></label>
                                <div class="col-lg-8">
                                    <input readonly name="currency" type="text"
                                           class="form-control" placeholder="Please Enter Currency">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Status</label>
                                <div class="col-lg-8">
                                    <select name="status" required class="form-control">
                                        <option value="1">Active</option>
                                        <option value="0">Inactive</option>
                                    </select>
                                </div>
                            </div>

                        </div>

                        <div class="col-md-12">
                            <hr>
                            <div class="form-group">
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary">Create New Notifications</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')

    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDZWL3BZwZLAwWcng7nGYKCBvyqMuV4mPA&libraries=places" type="text/javascript"></script>

    <script>

        var config_url = "{{url('/')}}";
        var autocomplete = new google.maps.places.Autocomplete((document.getElementById('location')), {types: ['geocode']});

        google.maps.event.addListener(autocomplete, 'place_changed', function() {
            var place = autocomplete.getPlace();
            var label_address  = place.adr_address;

            var lat = place.geometry.location.lat();
            var lng = place.geometry.location.lng();
            $('input[name="latitude"]').val(lat);
            $('input[name="longitude"]').val(lng);
            var latlng = new google.maps.LatLng(lat, lng);

            new google.maps.Geocoder().geocode({'latLng' : latlng}, function(results, status) {

                if (status == google.maps.GeocoderStatus.OK) {
                    if (results[1]) {
                        var country = null, countryCode = null, city = null, cityAlt = null;
                        var c, lc, component;
                        for (var r = 0, rl = results.length; r < rl; r += 1) {
                            var result = results[r];
                            if (!country && result.types[0] === 'country') {
                                country = result.address_components[0].long_name;
                                countryCode = result.address_components[0].short_name;
                            }

                            if (country) {
                                break;
                            }
                        }
                    }
                }
                var url = "{{url('currency-by-country')}}/"+country;
                $.get( url, function( data ) {

                    $('input[name="currency"]').val(data);
                });
            });
        });
    </script>
@endsection

resources/views/admin/notifications/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="bg-light lter b-b wrapper-md">
        <h1 class="m-n font-thin h3">Dashboard / Update Pattern</h1>
    </div>
    @include('admin.show_error_message')
    <div class="wrapper-md">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading font-bold">
                    <h4>Update A Pattern </h4>
                </div>
                <div class="panel-body">
                    <form class="bs-example form-horizontal" action="{{route('patterns.update', $pattern->_id)}}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        @method('PUT')

                        <div class="col-md-8 col-md-offset-2">
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Name</label>
                                <div class="col-lg-8">
                                    <input name="name"  value="{{ $pattern->name }}" required type="text" class="form-control" placeholder="Please Enter Ride Name">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Ride Type</label>
                                <div class="col-lg-8">
                                    <select name="ride_type_id" required class="form-control">
                                        @foreach($rideTypes as $rideType)

                                            <option @if($pattern->ride_type_id == $rideType->_id) selected='selected' @endif value="{{$rideType->_id}}">{{$rideType->name}}</option>

                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Range</label>
                                <div class="col-lg-8">
                                    <input name="range"  value="{{ $pattern->range }}" required type="number" step="0.01" class="form-control" placeholder="Please Enter Range">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Base Price</label>
                                <div class="col-lg-8">
                                    <input name="base_price" value="{{ $pattern->base_price }}" required type="number" step="0.01"  class="form-control" placeholder="Please Enter Base Price">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Minimum Ride Fare</label>
                                <div class="col-lg-8">
                                    <input name="min_ride_fare" value="{{ $pattern->min_ride_fare }}" required type="number" step="0.01" class="form-control" placeholder="Please Enter Minimum Ride Fare">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Kilometer Rate</label>
                                <div class="col-lg-8">
                                    <input name="km_rate" value="{{ $pattern->km_rate }}" required type="number" step="0.01" class="form-control" placeholder="Please Enter Kilometer Rate">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Minimum Rate</label>
                                <div class="col-lg-8">
                                    <input name="min_rate" value="{{ $pattern->min_rate }}" required type="number" step="0.01" class="form-control" placeholder="Please Enter Minimum Rate">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Location</label>
                                <div class="col-lg-8">
                                    <input name="location" id="location" value="{{ $pattern->location_string }}" required type="text"
                                           class="form-control" placeholder="Please Enter Location">
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="col-lg-4 col-md-offset-4">
                                            <input name="latitude" value="{{ $pattern->latitude }}" readonly required type="text"
                                                   class="form-control" placeholder="Latitude">
                                        </div>
                                        <div class="col-lg-4">
                                            <input name="longitude" value="{{ $pattern->longitude }}" readonly required type="text"
                                                   class="form-control" placeholder="Longitude">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-4 control-label">Currency <small class="text-danger">*auto added</small></label>
                                <div class="col-lg-8">
                                    <input readonly value="{{ $pattern->currency }}"  name="currency" type="text"
                                           class="form-control" placeholder="Please Enter Currency">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-4 control-label">Status</label>
                                <div class="col-lg-8">
                                    <select name="status" required class="form-control">
                                        <option @if($pattern->status == 1) selected='selected' @endif  value="1">Active</option>
                                        <option @if($pattern->status == 0) selected='selected' @endif  value="0">Inactive</option>
                                    </select>
                                </div>
                            </div>

                        </div>

                        <div class="col-md-12">
                            <hr>
                            <div class="form-group">
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary">Update Pattern</button>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')

    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDZWL3BZwZLAwWcng7nGYKCBvyqMuV4mPA&libraries=places" type="text/javascript"></script>

    <script>

        var config_url = "{{url('/')}}";
        var autocomplete = new google.maps.places.Autocomplete((document.getElementById('location')), {types: ['geocode']});

        google.maps.event.addListener(autocomplete, 'place_changed', function() {
            var place = autocomplete.getPlace();
            var label_address  = place.adr_address;

            var lat = place.geometry.location.lat();
            var lng = place.geometry.location.lng();
            $('input[name="latitude"]').val(lat);
            $('input[name="longitude"]').val(lng);
            var latlng = new google.maps.LatLng(lat, lng);

            new google.maps.Geocoder().geocode({'latLng' : latlng}, function(results, status) {

                if (status == google.maps.GeocoderStatus.OK) {
                    if (results[1]) {
                        var country = null, countryCode = null, city = null, cityAlt = null;
                        var c, lc, component;
                        for (var r = 0, rl = results.length; r < rl; r += 1) {
                            var result = results[r];
                            if (!country && result.types[0] === 'country') {
                                country = result.address_components[0].long_name;
                                countryCode = result.address_components[0].short_name;
                            }

                            if (country) {
                                break;
                            }
                        }
                    }
                }
                var url = "{{url('currency-by-country')}}/"+country;
                $.get( url, function( data ) {

                    $('input[name="currency"]').val(data);
                });
            });
        });
    </script>
@endsection

resources/views/admin/notifications/fcm_edit.blade.php
@extends('layouts.app')


@section('content')

    <div class="bg-light lter b-b wrapper-md">
        <h1 class="m-n font-thin h3">Dashboard / Update FCM Text</h1>
    </div>
    @include('admin.show_error_message')
    <div class="wrapper-md">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading font-bold">
                    <h4>Existing FCM Key</h4>
                </div>
                <div class="panel-body">
                    <form class="bs-example form-horizontal" action="{{route('notification.fcm.update',$fcmKey->_id)}}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        @method('PUT')

                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-lg-2 control-label">FCM URL</label>
                                <div class="col-lg-10">
                                    <input name="fcm_url"  value="{{$fcmKey->fcm_url}}" required type="text" class="form-control" placeholder="Please Enter FCM Url">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label">FCM Key</label>
                                <div class="col-lg-10">
                                    <input name="fcm_key_id"  value="{{$fcmKey->fcm_key_id}}" required type="text" class="form-control" placeholder="Please Enter FCM Key">
                                </div>
                            </div>

                        </div>

                        <div class="col-md-12">
                            <hr>
                            <div class="form-group">
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary">Update FCM Info</button>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')

    <script src="{{ asset('libs/jquery/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        $('input[name="start_date"]').datepicker({
            format: "dd-mm-yyyy",
            autoclose: true,
            todayHighlight: true
        });
        $('input[name="expiration_date"]').datepicker({
            format: "dd-mm-yyyy",
            autoclose: true,
            todayHighlight: true
        });
    </script>

@endsection

resources/views/admin/notifications/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="bg-light lter b-b wrapper-md row">
        <div class="col-md-10">
            <h1 class="m-n font-thin h3">Dashboard / All Notifications</h1>
        </div>

    </div>
    <div class="wrapper-md">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>All Notifications List</h4>
            </div>
            <div class="table-responsive">
                <table id="driver_table" ui-jq="dataTable" ui-options="{sAjaxSource: '{{route('notifications.json')}}',
              aoColumns: allNotificationColumns
        }" class="table table-striped b-t b-b">
                    <thead>
                    <tr>
                        <th class="col-md-2">Title</th>
                        <th class="col-md-3">Message</th>
                        <th class="col-md-1">type</th>
                        <th class="col-md-1">Image</th>
                        <th class="col-md-1">Status</th>
                        <th class="col-md-1">Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection

@section('script')
    <script>
        var allNotificationColumns = [
            {mData: 'title'},
            {mData: 'description'},
            {mData: 'type'},
            {
                mData: 'image',
                render: function (data, type, row, meta) {
                    if(data){

                        return '<img src="{{asset('storage/notifications/')}}/' + data + '" class="img-responsive" style="width: auto; height: 70px;">';
                    }else{
                        return '<img src="{{asset('storage/images/no_image.jpg')}}" class="img-responsive" style="width: auto; height: 70px;">';
                    }
                }
            },
            {
                mData: 'status',
                render: function (data, type, row, meta) {
                    if(data == 1){
                        return '<span class="label label-success">Success</span>';
                    }else{
                        return '<span class="label label-danger">Failed</span>';
                    }
                }
            },
            {mData: 'created_at'},
        ];
    </script>
@endsection