routes/web.php
<?php


Route::get('/', function () {
    return view('welcome');
});

//Auth::routes();

// Authentication Routes...



Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// switched off Registration Routes...
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');


Route::middleware(['auth'])->group(function () {

    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/home', 'DashboardController@index')->name('dashboard');

    Route::get('/bookings', 'BookingController@index')->name('all.bookings');
    Route::get('/bookings-json', 'BookingController@allBookingsJson')->name('all.bookings.json');

    Route::get('/bookings/{parameter}', 'BookingController@showSplitBooking')->name('split.bookings');
    Route::get('/bookings-json/{parameter}', 'BookingController@returnSplitBookingJson')->name('split.bookings.json');
    /*
     * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
     */
    Route::get('/customers', 'CustomerController@index')->name('all.customers');
    Route::get('/customers-json', 'CustomerController@allCustomersJson')->name('all.customers.json');
    Route::get('/customers-json/{id}', 'CustomerController@singleCustomersJson');
    Route::get('/customers/{customer}/edit', 'CustomerController@edit');
    Route::put('/customers/{customer}', 'CustomerController@update')->name('customers.update');;
    Route::delete('/customers/{customer}', 'CustomerController@delete');

    /*
     * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
     */
    Route::get('/drivers', 'DriverController@index')->name('all.drivers');
    Route::get('/drivers-json', 'DriverController@allDriverJson')->name('all.drivers.json');
    Route::get('/drivers-json/{driver}', 'DriverController@singleDriverJson');
    Route::get('/drivers/{driver}/edit', 'DriverController@edit');
    Route::get('/drivers/create', 'DriverController@create')->name('drivers.create');
    Route::post('/drivers', 'DriverController@store')->name('drivers.store');
    Route::put('/drivers/{driver}', 'DriverController@update')->name('all.driver.update');;
    Route::delete('/drivers/{driver}', 'DriverController@delete');
    /*
     * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
     */
    Route::get('/drivers/{driver}/payment', 'TransactionController@showPaymentPage')->name('driver.payment.create');
    Route::post('/drivers/{driver}/payment', 'TransactionController@paymentCalculate')->name('driver.payment.store');
    Route::get('/transaction', 'TransactionController@index')->name('all.transaction');
    Route::get('/transaction-json', 'TransactionController@allTransactionJson')->name('all.transaction.json');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::resource('rides', 'RideTypesController');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('currency-by-country/{countryName}', 'PatternController@getCurrencyByCountryName');
    Route::resource('patterns', 'PatternController')->except(['show']);
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::resource('helps', 'HelpTableController');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::resource('promocodes', 'PromocodeController')->except(['show', 'destroy']);
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('documents-json', 'DriverDocumentController@getDocumentJson')->name('driver-documents.json');
    Route::get('driver-documents/{driver}', 'DriverDocumentController@getAllDocumentsOfDriver');
    Route::resource('documents', 'DriverDocumentController')->except(['edit']);
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('feedbacks', 'FeedbackController@index')->name('feedbacks.index');
    Route::get('feedbacks-json', 'FeedbackController@getFeedbackJson')->name('feedbacks.json');
    Route::get('feedbacks/{feedback}', 'FeedbackController@show');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('requests', 'RequestController@index')->name('requests.index');
    Route::get('requests/{request}', 'RequestController@show');
    Route::get('requests-json', 'RequestController@getRequestsJson')->name('requests.json');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('fcms', 'NotificationController@viewFcmPage')->name('notifications.fcm');
    Route::put('fcms/{fcm}/edit', 'NotificationController@editFcm')->name('notification.fcm.update');

    Route::get('notifications-json', 'NotificationController@getNotificationJson')->name('notifications.json');

    Route::get('notifications', 'NotificationController@index')->name('notifications.index');
    Route::get('notifications/create', 'NotificationController@create')->name('notifications.create');
    Route::post('notifications', 'NotificationController@store')->name('notifications.store');
    /*
     * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
     */
    Route::get('settings', 'SettingController@edit')->name('settings.edit');
    Route::put('settings/{setting}/edit', 'SettingController@update')->name('settings.update');

});

Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');

app/Promocode.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Promocode extends Eloquent
{
    protected $dates = ['start_date', 'expiration_date'];
}

app/Http/Controllers/PromocodeController.php
<?php

namespace App\Http\Controllers;

use App\Promocode;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use MongoDB\BSON\UTCDateTime;

class PromocodeController extends Controller
{
    /**
     * Display a listing of the resource
     */
    public function index()
    {
        $promocodes = Promocode::all();

        return view('admin.promocodes.index')->with('promocodes', $promocodes);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.promocodes.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Promocode $promocode)
    {

        return view('admin.promocodes.edit')->with('promocode', $promocode);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Promocode $promocode)
    {

        $this->validator($request->all())->validate();

        $promocode->code = $request->code ;
        $promocode->start_date = new UTCDateTime(strtotime($request->start_date) * 1000) ;
        $promocode->expiration_date = new UTCDateTime(strtotime($request->expiration_date) * 1000) ;
        $promocode->offer = $request->offer ;
        $promocode->status = $request->status ;

        $promocode->save();

        return redirect()->route('promocodes.edit', $promocode->_id)->with('success', 'Promocode Successfully Created');

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        //
    }


    /**
     * Validate the requeste
     */
    public function validator(array $requestData)
    {
        return Validator::make($requestData,
            [
                'code' => 'required',
                'start_date' => 'required',
                'expiration_date' => 'required',
                'offer' => 'required',
            ]);
    }
}

resources/views/admin/promocodes/create.blade.php
@extends('layouts.app')

@section('style')

    <link rel="stylesheet" href="{{ asset('libs/jquery/bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}" type="text/css"/>
@endsection

@section('content')

    <div class="bg-light lter b-b wrapper-md">
        <h1 class="m-n font-thin h3">Dashboard / Create Promocode Text</h1>
    </div>
    @include('admin.show_error_message')
    <div class="wrapper-md">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading font-bold">
                    <h4>Create New Help Text</h4>
                </div>
                <div class="panel-body">
                    <form class="bs-example form-horizontal" action="{{route('promocodes.store')}}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Code</label>
                                <div class="col-lg-10">
                                    <input name="code"  value="{{ old('code') }}" required type="text" class="form-control" placeholder="Please Enter Code">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label">Start Date</label>
                                <div class="col-lg-10">
                                    <input name="start_date"  value="{{ old('start_date') }}" required type="text" class="form-control" placeholder="Please Enter Start date">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label">Expiration Date</label>
                                <div class="col-lg-10">
                                    <input name="expiration_date"  value="{{ old('expiration_date') }}" required type="text" class="form-control" placeholder="Please Enter Start date">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label">Offer</label>
                                <div class="col-lg-10">
                                    <input name="offer"  value="{{ old('offer') }}" required type="text" class="form-control" placeholder="Please Enter Start date">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label">Status</label>
                                <div class="col-lg-10">
                                    <select name="status" required class="form-control">
                                        <option value="1">Active</option>
                                        <option value="0">Inactive</option>
                                    </select>
                                </div>
                            </div>

                        </div>

                        <div class="col-md-12">
                            <hr>
                            <div class="form-group">
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary">Create New Promocode</button>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')

    <script src="{{ asset('libs/jquery/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        $('input[name="start_date"]').datepicker({
            format: "dd-mm-yyyy",
            autoclose: true,
            todayHighlight: true
        });
        $('input[name="expiration_date"]').datepicker({
            format: "dd-mm-yyyy",
            autoclose: true,
            todayHighlight: true
        });
    </script>

@endsection

resources/views/admin/promocodes/edit.blade.php
@extends('layouts.app')

@section('style')

    <link rel="stylesheet" href="{{ asset('libs/jquery/bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}" type="text/css"/>
@endsection
@section('content')

    <div class="bg-light lter b-b wrapper-md">
        <h1 class="m-n font-thin h3">Dashboard / Update Promocode</h1>
    </div>
    @include('admin.show_error_message')
    <div class="wrapper-md">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading font-bold">
                    <h4>Update A Promocode </h4>
                </div>
                <div class="panel-body">
                    <form class="bs-example form-horizontal" action="{{route('promocodes.update', $promocode->_id)}}" method="post" enctype="multipart/form-data">

                        {{ csrf_field() }}

                        @method('PUT')

                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Code</label>
                                <div class="col-lg-10">
                                    <input name="code"  value="{{ $promocode->code }}" required type="text" class="form-control" placeholder="Please Enter Code">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label">Start Date</label>
                                <div class="col-lg-10">
                                    <input name="start_date"  value="{{ date('d-m-Y', strtotime($promocode->start_date)) }}" required type="text" class="form-control" placeholder="Please Enter Start date">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label">Expiration Date</label>
                                <div class="col-lg-10">
                                    <input name="expiration_date"  value="{{ date('d-m-Y', strtotime($promocode->expiration_date)) }}" required type="text" class="form-control" placeholder="Please Enter Start date">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label">Offer</label>
                                <div class="col-lg-10">
                                    <input name="offer"  value="{{ $promocode->offer }}" required type="text" class="form-control" placeholder="Please Enter Start date">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label">Status</label>
                                <div class="col-lg-10">
                                    <select name="status" required class="form-control">
                                        <option @if($promocode->status == 1) selected='selected' @endif  value="1">Active</option>
                                        <option @if($promocode->status == 0) selected='selected' @endif   value="0">Inactive</option>
                                    </select>
                                </div>
                            </div>

                        </div>
                        
                        <div class="col-md-12">
                            <hr>
                            <div class="form-group">
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary">Update Promocode</button>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')

    <script src="{{ asset('libs/jquery/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
    <script>
        $('input[name="start_date"]').datepicker({
            format: "dd-mm-yyyy",
            autoclose: true,
            todayHighlight: true
        });
        $('input[name="expiration_date"]').datepicker({
            format: "dd-mm-yyyy",
            autoclose: true,
            todayHighlight: true
        });
    </script>

@endsection

resources/views/admin/promocodes/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="bg-light lter b-b wrapper-md row">
        <div class="col-md-10">
            <h1 class="m-n font-thin h3">Dashboard / All Promocode</h1>
        </div>
        <div class="col-md-2">
            <a href="{{route('promocodes.create')}}" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i>&nbsp;&nbsp;Create New Promocode</a>
        </div>
    </div>

    <div class="wrapper-md">
        <div class="panel panel-default">
            <div class="panel-heading">
                View All Promocodes
            </div>
            <div class="panel-body">
                <table id="promocode-type-data" class="table table-bordered">
                    <thead>
                    <tr>
                        <th class="col-md-1">SL</th>
                        <th class="col-md-1">Code</th>
                        <th class="col-md-2">Start Date</th>
                        <th class="col-md-2">Expiration Date</th>
                        <th class="col-md-1">Offer Amount</th>
                        <th class="col-md-1">Status</th>
                        <th class="col-md-1">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($promocodes as $promocode)
                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>{{$promocode->code}}</td>
                        <td>{{ date('d M Y', strtotime($promocode->start_date)) }}</td>
                        <td>{{ date('d M Y', strtotime($promocode->expiration_date)) }}</td>
                        <td>{{$promocode->off}}</td>

                        <td>
                            @if($promocode->status == 0)
                                <label class="label bg-warning">Inactive</label>
                            @elseif($promocode->status == 1)
                                <label class="label bg-success">Active</label>
                            @elseif($promocode->status == 2)
                                <label class="label bg-danger">Deleted</label>
                            @endif
                        </td>
                        <td>
                            <a href="{{route('promocodes.edit', $promocode->_id)}}" class="btn btn-primary btn-xs btn-block">Edit</a>
                        </td>
                    </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>



@endsection