routes/web.php
<?php


Route::get('/', function () {
    return view('welcome');
});

//Auth::routes();

// Authentication Routes...



Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// switched off Registration Routes...
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');


Route::middleware(['auth'])->group(function () {

    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/home', 'DashboardController@index')->name('dashboard');

    Route::get('/bookings', 'BookingController@index')->name('all.bookings');
    Route::get('/bookings-json', 'BookingController@allBookingsJson')->name('all.bookings.json');

    Route::get('/bookings/{parameter}', 'BookingController@showSplitBooking')->name('split.bookings');
    Route::get('/bookings-json/{parameter}', 'BookingController@returnSplitBookingJson')->name('split.bookings.json');
    /*
     * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
     */
    Route::get('/customers', 'CustomerController@index')->name('all.customers');
    Route::get('/customers-json', 'CustomerController@allCustomersJson')->name('all.customers.json');
    Route::get('/customers-json/{id}', 'CustomerController@singleCustomersJson');
    Route::get('/customers/{customer}/edit', 'CustomerController@edit');
    Route::put('/customers/{customer}', 'CustomerController@update')->name('customers.update');;
    Route::delete('/customers/{customer}', 'CustomerController@delete');

    /*
     * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
     */
    Route::get('/drivers', 'DriverController@index')->name('all.drivers');
    Route::get('/drivers-json', 'DriverController@allDriverJson')->name('all.drivers.json');
    Route::get('/drivers-json/{driver}', 'DriverController@singleDriverJson');
    Route::get('/drivers/{driver}/edit', 'DriverController@edit');
    Route::get('/drivers/create', 'DriverController@create')->name('drivers.create');
    Route::post('/drivers', 'DriverController@store')->name('drivers.store');
    Route::put('/drivers/{driver}', 'DriverController@update')->name('all.driver.update');;
    Route::delete('/drivers/{driver}', 'DriverController@delete');
    /*
     * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
     */
    Route::get('/drivers/{driver}/payment', 'TransactionController@showPaymentPage')->name('driver.payment.create');
    Route::post('/drivers/{driver}/payment', 'TransactionController@paymentCalculate')->name('driver.payment.store');
    Route::get('/transaction', 'TransactionController@index')->name('all.transaction');
    Route::get('/transaction-json', 'TransactionController@allTransactionJson')->name('all.transaction.json');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::resource('rides', 'RideTypesController');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('currency-by-country/{countryName}', 'PatternController@getCurrencyByCountryName');
    Route::resource('patterns', 'PatternController')->except(['show']);
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::resource('helps', 'HelpTableController');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::resource('promocodes', 'PromocodeController')->except(['show', 'destroy']);
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('documents-json', 'DriverDocumentController@getDocumentJson')->name('driver-documents.json');
    Route::get('driver-documents/{driver}', 'DriverDocumentController@getAllDocumentsOfDriver');
    Route::resource('documents', 'DriverDocumentController')->except(['edit']);
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('feedbacks', 'FeedbackController@index')->name('feedbacks.index');
    Route::get('feedbacks-json', 'FeedbackController@getFeedbackJson')->name('feedbacks.json');
    Route::get('feedbacks/{feedback}', 'FeedbackController@show');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('requests', 'RequestController@index')->name('requests.index');
    Route::get('requests/{request}', 'RequestController@show');
    Route::get('requests-json', 'RequestController@getRequestsJson')->name('requests.json');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('fcms', 'NotificationController@viewFcmPage')->name('notifications.fcm');
    Route::put('fcms/{fcm}/edit', 'NotificationController@editFcm')->name('notification.fcm.update');

    Route::get('notifications-json', 'NotificationController@getNotificationJson')->name('notifications.json');

    Route::get('notifications', 'NotificationController@index')->name('notifications.index');
    Route::get('notifications/create', 'NotificationController@create')->name('notifications.create');
    Route::post('notifications', 'NotificationController@store')->name('notifications.store');
    /*
     * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
     */
    Route::get('settings', 'SettingController@edit')->name('settings.edit');
    Route::put('settings/{setting}/edit', 'SettingController@update')->name('settings.update');

});

Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');

resources/views/admin/documents/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="row bg-light lter b-b wrapper-md">
        <div class="col-md-12">
            <h1 class="m-n font-thin h3">Dashboard / All Drivers Documents</h1>
        </div>
    </div>
    <div class="wrapper-md">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>All Drivers Documents List</h4>
                <small id="show_response" class="text-info"></small>
            </div>
            <div class="panel-body table-responsive">
                <table id="driver_document_table" ui-jq="dataTable"
                       ui-options="{sAjaxSource: '{{route('driver-documents.json')}}',
              aoColumns: allDriverColumns
        }" class="table table-striped b-t b-b">
                    <thead>
                    <tr>
                        <th class="col-md-2">Name</th>
                        <th class="col-md-9 text-center">Driver document</th>
                        <th class="col-md-1">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="modal fade" id="driverDocumentModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

            </div>
        </div>
    </div>


    <div class="modal fade" id="singleDocumentModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        var allDriverColumns = [
            {mData: 'driver_name'},
            {mData: 'driver_document'},
            {
                mData: '_id',
                render: function (data, type, row, meta) {
                    return '<button id="driverDocument" type="button"' +
                        'class="btn btn-sm btn-block btn-dark btn-addon"' +
                        'data-toggle="modal" data-target="#driverDocumentModal"' +
                        'data-id="' + data + '">Details</button>';
                }
            },
        ];

        $('table#driver_document_table').on('click', 'button#driverDocument', function () {
            var id = $(this).data('id');

            $.get("{{url('driver-documents')}}/" + id, function (response) {

                $('#driverDocumentModal .modal-content').html(response);
            });
        })

        var documentBtn;

        $('table#driver_document_table').on('click', 'span.singleDocument', function () {

            documentBtn = $(this);
            var id = documentBtn.data('id');

            $.get("{{url('documents')}}/" + id, function (response) {

                $('#singleDocumentModal .modal-content').html(response);

            });
        });

        $('#singleDocumentModal').on('submit', 'form#documents_update', function (event) {

            event.preventDefault();
            var form = $(this);
            var formData = form.serialize();
            var url = form.attr('action');

            $.post( url, formData, function( responses ) {

                documentBtn.removeClass();
                documentBtn.addClass('btn singleDocument m-l-xs m-b-xs btn-xs');
                documentBtn.addClass('btn-' + responses.css_color);
                $('small#show_response').html(responses.message);

                $("#singleDocumentModal").modal("hide");

            }, "json");


        })

    </script>
@endsection

resources/views/admin/documents/modal_documents_of_driver.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">All Driver's Documents</h4>
</div>
<div class="modal-body">
    <div class="panel-group">

        @foreach( $documents as $document)
            <div class="panel panel-{{$allCssColor[$document->status]}}">
                <div class="panel-heading">
                    {{\App\DriverDocument::documentTypeName($document->type)}}
                </div>
                <div class="panel-body text-center">
                    @if(isset($document->image) && !empty($document->image))
                        <img class="img-responsive" src="{{asset('storage/driver_document/'.$document->image)}}"
                             alt="driver document">
                    @else
                        <img class="img-responsive" src="{{asset('storage/images/no_image.jpg')}}" alt="driver document" style="width: 130px; height: auto;">
                    @endif
                </div>
                <div class="panel-footer text-center">
                    <div class="label label-{{$allCssColor[$document->status]}}"> Status : {{\App\DriverDocument::getAllStatusAsTextOfDocuments()[$document->status]}}</div>
                </div>
            </div>

        @endforeach
    </div>
</div>
<div class="modal-footer">
    <div class="text-center">
        <button type="button" class="btn btn-default" data-dismiss="modal">CLOSE</button>
    </div>

</div>

resources/views/admin/documents/modal_single_documents_of_driver.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
    <div class="text-center modal-title">
        <h4>Driver : {{$document->driver->driver_name}}</h4>
        <h5>{{$document->type_name}}</h5>
    </div>
</div>

<div class="modal-body">
    <img src="{{asset('storage/driver_document/'.$document->image)}}" class="img-responsive img-thumbnail" alt="">
</div>
<div class="modal-footer">
    <div class="text-center row" style="padding:20px">
        <form id="documents_update" action="{{route('documents.update', $document->_id)}}">
            {{ csrf_field() }}

            @method('PUT')
            <div class="col-md-4 col-md-offset-2">
                <select name="status" class="form-control bg-{{$document->status_css}}">
                    <option @if($document->status == 0) selected @endif value="0">Not Defined</option>
                    <option @if($document->status == 1) selected @endif value="1">Pending</option>
                    <option @if($document->status == 2) selected @endif value="2">Approve</option>
                    <option @if($document->status == 3) selected @endif value="3">Rejected</option>
                </select>
            </div>
            <div class="col-md-4">
                <div class="btn-group">
                    <button class="btn btn-{{$document->status_css}}" type="submit">Update</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>

                </div>
            </div>


        </form>
    </div>
</div>