routes/web.php
<?php


Route::get('/', function () {
    return view('welcome');
});

//Auth::routes();

// Authentication Routes...



Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// switched off Registration Routes...
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');


Route::middleware(['auth'])->group(function () {

    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/home', 'DashboardController@index')->name('dashboard');

    Route::get('/bookings', 'BookingController@index')->name('all.bookings');
    Route::get('/bookings-json', 'BookingController@allBookingsJson')->name('all.bookings.json');

    Route::get('/bookings/{parameter}', 'BookingController@showSplitBooking')->name('split.bookings');
    Route::get('/bookings-json/{parameter}', 'BookingController@returnSplitBookingJson')->name('split.bookings.json');
    /*
     * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
     */
    Route::get('/customers', 'CustomerController@index')->name('all.customers');
    Route::get('/customers-json', 'CustomerController@allCustomersJson')->name('all.customers.json');
    Route::get('/customers-json/{id}', 'CustomerController@singleCustomersJson');
    Route::get('/customers/{customer}/edit', 'CustomerController@edit');
    Route::put('/customers/{customer}', 'CustomerController@update')->name('customers.update');;
    Route::delete('/customers/{customer}', 'CustomerController@delete');

    /*
     * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
     */
    Route::get('/drivers', 'DriverController@index')->name('all.drivers');
    Route::get('/drivers-json', 'DriverController@allDriverJson')->name('all.drivers.json');
    Route::get('/drivers-json/{driver}', 'DriverController@singleDriverJson');
    Route::get('/drivers/{driver}/edit', 'DriverController@edit');
    Route::get('/drivers/create', 'DriverController@create')->name('drivers.create');
    Route::post('/drivers', 'DriverController@store')->name('drivers.store');
    Route::put('/drivers/{driver}', 'DriverController@update')->name('all.driver.update');;
    Route::delete('/drivers/{driver}', 'DriverController@delete');
    /*
     * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
     */
    Route::get('/drivers/{driver}/payment', 'TransactionController@showPaymentPage')->name('driver.payment.create');
    Route::post('/drivers/{driver}/payment', 'TransactionController@paymentCalculate')->name('driver.payment.store');
    Route::get('/transaction', 'TransactionController@index')->name('all.transaction');
    Route::get('/transaction-json', 'TransactionController@allTransactionJson')->name('all.transaction.json');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::resource('rides', 'RideTypesController');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('currency-by-country/{countryName}', 'PatternController@getCurrencyByCountryName');
    Route::resource('patterns', 'PatternController')->except(['show']);
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::resource('helps', 'HelpTableController');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::resource('promocodes', 'PromocodeController')->except(['show', 'destroy']);
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('documents-json', 'DriverDocumentController@getDocumentJson')->name('driver-documents.json');
    Route::get('driver-documents/{driver}', 'DriverDocumentController@getAllDocumentsOfDriver');
    Route::resource('documents', 'DriverDocumentController')->except(['edit']);
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('feedbacks', 'FeedbackController@index')->name('feedbacks.index');
    Route::get('feedbacks-json', 'FeedbackController@getFeedbackJson')->name('feedbacks.json');
    Route::get('feedbacks/{feedback}', 'FeedbackController@show');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('requests', 'RequestController@index')->name('requests.index');
    Route::get('requests/{request}', 'RequestController@show');
    Route::get('requests-json', 'RequestController@getRequestsJson')->name('requests.json');
    /*
    * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    */
    Route::get('fcms', 'NotificationController@viewFcmPage')->name('notifications.fcm');
    Route::put('fcms/{fcm}/edit', 'NotificationController@editFcm')->name('notification.fcm.update');

    Route::get('notifications-json', 'NotificationController@getNotificationJson')->name('notifications.json');

    Route::get('notifications', 'NotificationController@index')->name('notifications.index');
    Route::get('notifications/create', 'NotificationController@create')->name('notifications.create');
    Route::post('notifications', 'NotificationController@store')->name('notifications.store');
    /*
     * =-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
     */
    Route::get('settings', 'SettingController@edit')->name('settings.edit');
    Route::put('settings/{setting}/edit', 'SettingController@update')->name('settings.update');

});

Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');

app/HelpTable.php
<?php

namespace App;


use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class HelpTable extends Eloquent
{

    public function helpReview(){

        return $this->hasMany('App\HelpReview', 'help_id');
    }


    public function likes(){

        return $this->helpReview->where('help_status', 1)->count();

    }
    public function dislike(){

        return $this->helpReview->where('help_status', 0)->count();

    }

}

resources/views/admin/helps/create.blade.php
@extends('layouts.app')

@section('style')

    <style>
        .wysihtml5-sandbox{

            width: 100%!important;
        }
    </style>
    <link rel="stylesheet" href="{{ asset('libs/jquery/bootstrap3-wysiwyg/bootstrap3-wysihtml5.min.css') }}" type="text/css"/>
@endsection

@section('content')

    <div class="bg-light lter b-b wrapper-md">
        <h1 class="m-n font-thin h3">Dashboard / Create Help Text</h1>
    </div>
    @include('admin.show_error_message')
    <div class="wrapper-md">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading font-bold">
                    <h4>Create New Help Text</h4>
                </div>
                <div class="panel-body">
                    <form class="bs-example form-horizontal" action="{{route('helps.store')}}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Head</label>
                                <div class="col-lg-10">
                                    <input name="head"  value="{{ old('head') }}" required type="text" class="form-control" placeholder="Please Enter Help Head">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label">Status</label>
                                <div class="col-lg-10">
                                    <select name="status" required class="form-control">
                                        <option value="1">Active</option>
                                        <option value="0">Inactive</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Upload Image</label>
                                <div class="col-lg-6">
                                    <input name="image"  ui-jq="filestyle" ui-options="{icon: false, buttonName: 'btn-info'}" type="file">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label">Content</label>
                                <div class="col-lg-10">
                                    <textarea name="contents" value="{{ old('contents') }}" class="form-control"></textarea>
                                </div>
                            </div>

                        </div>

                        <div class="col-md-12">
                            <hr>
                            <div class="form-group">
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary">Create New Help</button>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')

    <script src="{{ asset('libs/jquery/bootstrap3-wysiwyg/bootstrap3-wysihtml5.all.min.js') }}"></script>
    <script src="{{ asset('libs/jquery/bootstrap3-wysiwyg/bootstrap3-wysihtml5.min.js') }}"></script>
    <script>
        $('textarea[name="contents"]').wysihtml5();
    </script>

@endsection

resources/views/admin/helps/edit.blade.php
@extends('layouts.app')
@section('style')

    <link rel="stylesheet" href="{{ asset('libs/jquery/bootstrap3-wysiwyg/bootstrap3-wysihtml5.min.css') }}" type="text/css"/>
@endsection
@section('content')

    <div class="bg-light lter b-b wrapper-md">
        <h1 class="m-n font-thin h3">Dashboard / Update Help</h1>
    </div>
    @include('admin.show_error_message')
    <div class="wrapper-md">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading font-bold">
                    <h4>Update A Help </h4>
                </div>
                <div class="panel-body">
                    <form class="bs-example form-horizontal" action="{{route('helps.update', $help->_id)}}" method="post" enctype="multipart/form-data">
                        
                        {{ csrf_field() }}

                        @method('PUT')

                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-lg-2 control-label">Head</label>
                                <div class="col-lg-10">
                                    <input name="head"  value="{{ $help->head}}" required type="text" class="form-control" placeholder="Please Enter Help Head">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label">Status</label>
                                <div class="col-lg-10">
                                    <select name="status" required class="form-control">
                                        <option @if($help->status == 1) selected='selected' @endif  value="1">Active</option>
                                        <option @if($help->status == 0) selected='selected' @endif   value="0">Inactive</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label">Content</label>
                                <div class="col-lg-10">
                                    <textarea name="contents" class="form-control">{{$help->content }}</textarea>
                                </div>
                            </div>


                            <div class="form-group">
                                <label class="col-lg-2 control-label">Upload Image</label>
                                <div class="col-lg-4">
                                    <input name="image"  ui-jq="filestyle" ui-options="{icon: false, buttonName: 'btn-info'}" type="file">
                                </div>
                                <div class="col-lg-6">
                                    <img src="{{asset('storage/images/'.$help->image)}}" width="100px;" height="100px" />
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-md-12">
                            <hr>
                            <div class="form-group">
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary">Update Help</button>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')

    <script src="{{ asset('libs/jquery/bootstrap3-wysiwyg/bootstrap3-wysihtml5.all.min.js') }}"></script>
    <script src="{{ asset('libs/jquery/bootstrap3-wysiwyg/bootstrap3-wysihtml5.min.js') }}"></script>
    <script>
        $('textarea[name="contents"]').wysihtml5();
    </script>

@endsection

resources/views/admin/helps/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="bg-light lter b-b wrapper-md row">
        <div class="col-md-10">
            <h1 class="m-n font-thin h3">Dashboard / All Help Text</h1>
        </div>
        <div class="col-md-2">
            <a href="{{route('helps.create')}}" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i>&nbsp;&nbsp;Create New Help</a>
        </div>
    </div>

    <div class="wrapper-md">
        <div class="panel panel-default">
            <div class="panel-heading">
                View All help Text
            </div>
            <div class="panel-body">
                <table id="help-type-data" class="table table-bordered">
                    <thead>
                    <tr>
                        <th class="col-md-1">ID</th>
                        <th class="col-md-1">Head</th>
                        <th class="col-md-2">Ratings</th>
                        <th class="col-md-3">Image</th>
                        <th class="col-md-1">Status</th>
                        <th class="col-md-3">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($helpTable as $help)
                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>{{$help->head}}</td>
                        <td>Like : {{$help->likes()}} || Dislikes :  {{$help->dislike()}}</td>
                        <td>
                            @if(!empty($help->image))
                                <img src="{{asset('storage/images/'.$help->image)}}"  style="width: 130px;height:auto;" alt="help image">
                            @else
                                <img src="{{asset('storage/images/no_image.jpg')}}"  style="width: 130px;height:auto;" alt="help image">
                            @endif
                        </td>
                        <td>
                            @if($help->status == 0)
                                <label class="label bg-warning">Inactive</label>
                            @elseif($help->status == 1)
                                <label class="label bg-success">Active</label>
                            @elseif($help->status == 2)
                                <label class="label bg-danger">Deleted</label>
                            @endif
                        </td>
                        <td>
                            <div class="btn-group">
                                <button id="helpDetailsModal" type="button" class="btn btn-sm btn-primary btn-addon"
                                        data-toggle="modal" data-target="#helpDetails" data-id="{{$help->_id}}">Details</button>

                                <a href="{{route('helps.edit', $help->_id)}}" class="btn btn-sm btn-dark">Edit</a>

                                <form action="{{route('helps.destroy', $help->_id)}}" method="post" style=" display: inline;">
                                    <input type="hidden" name="_method" value="delete">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <button onclick="return confirm('Are you sure?')" class="btn btn-sm btn-danger" type="submit">Delete</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>


    <div class="modal fade" id="helpDetails" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Details of Help Text</h4>
                </div>
                <div class="modal-body">
                    <div class="panel panel-default">
                        <div class="panel-heading"><span id="help_name"></span></div>
                        <table id="modal_help_details" class="table table-striped m-b-none">
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $('table#help-type-data').on('click', 'button#helpDetailsModal', function () {
            var id = $(this).data('id');

            $.get("{{url('helps')}}/" + id, function (response) {

                var generatedTableHtml = '';
                $.each(response, function (key, value) {
                    var keySting = key.replace(/_/gi, ' ');
                    var UpperCaseKey = keySting[0].toUpperCase() + keySting.substr(1);

                    generatedTableHtml += '<tr><td>' + UpperCaseKey + '</td>' +
                        '<td>' + value + '</td></tr>';
                });

                $('#helpDetails table#modal_help_details tbody').html(generatedTableHtml)

            }, "json");
        })
    </script>
@endsection